-- EduFit (ClassFit AI 출강 신청) Supabase 스키마
-- 사용법: Supabase 대시보드 → SQL Editor → 전체 붙여넣기 → Run
-- 비로그인(anon) 신청 구조: 누구나 신청(INSERT) 가능, 교사 개인정보(teacher_info)는 조회 불가

-- 1. 신청 마스터
create table if not exists public.form_submissions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  status text default '접수완료',
  user_id uuid -- 과거 로그인 구조 호환용, 현재 미사용(null)
);

-- 2. 학교 정보
create table if not exists public.school_info (
  id bigint generated by default as identity primary key,
  submission_id uuid references public.form_submissions(id) on delete cascade,
  type text,
  name text,
  area text
);

-- 3. 교사 정보 (개인정보 — anon 조회 금지)
create table if not exists public.teacher_info (
  id bigint generated by default as identity primary key,
  submission_id uuid references public.form_submissions(id) on delete cascade,
  name text,
  phone text
);

-- 4. 학생 정보
create table if not exists public.student_info (
  id bigint generated by default as identity primary key,
  submission_id uuid references public.form_submissions(id) on delete cascade,
  target_grade text,
  student_count integer,
  level text
);

-- 5. 교육 구성
create table if not exists public.education_config (
  id bigint generated by default as identity primary key,
  submission_id uuid references public.form_submissions(id) on delete cascade,
  resources jsonb,
  goals jsonb,
  period text,
  date text
);

-- RLS 활성화
alter table public.form_submissions enable row level security;
alter table public.school_info      enable row level security;
alter table public.teacher_info     enable row level security;
alter table public.student_info     enable row level security;
alter table public.education_config enable row level security;

-- 신청(INSERT): 비로그인 포함 누구나 가능
create policy "anon insert" on public.form_submissions for insert to anon, authenticated with check (true);
create policy "anon insert" on public.school_info      for insert to anon, authenticated with check (true);
create policy "anon insert" on public.teacher_info     for insert to anon, authenticated with check (true);
create policy "anon insert" on public.student_info     for insert to anon, authenticated with check (true);
create policy "anon insert" on public.education_config for insert to anon, authenticated with check (true);

-- 조회(SELECT): '내 신청 내역' 화면용 — 교사 개인정보 테이블은 제외
create policy "anon select" on public.form_submissions for select to anon, authenticated using (true);
create policy "anon select" on public.school_info      for select to anon, authenticated using (true);
create policy "anon select" on public.student_info     for select to anon, authenticated using (true);
-- teacher_info, education_config는 SELECT 정책 없음 = anon 조회 불가 (관리자는 대시보드/service_role로 확인)
